Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK, pull requests merged in 2022-11, with the labels that each got.

#54 S05 movies tv fix issues
  src/components/Card.jsx
  src/components/Categories.jsx
  src/components/Popup.jsx
  src/pages/detail/Movie.jsx
  src/pages/detail/Tv.jsx
Labels: changes requested

#57 S05 us11 person responsive
  src/pages/detail/Person.jsx
  src/pages/detail/Person.scss
Labels: Correction done, Review needed

#75 fix navabar map
  src/components/navbar/Navbar.jsx
Labels: Review needed

#62 S05 manage 404 on tv shows and movies
  src/components/Card.jsx
  src/components/Categories.jsx
  src/components/carousel/Carousel.jsx
  src/components/carousel/carousel.css
  src/pages/detail/Movie.jsx
  src/pages/detail/Tv.jsx
Labels: Correction done, Review needed

#91 Hotfix person
  src/components/Card.jsx
  src/components/VideoPlayer.jsx
  src/components/guide/Guide.jsx
  src/pages/detail/Person.jsx
Labels: Review needed
