Repository WildCodeSchool/2022-09-Orleans-CDA-Projet-Frontend-EDPK, pull requests merged in 2022-10, with the labels that each got.

#1 Home Page color + video header + sass installed
  README.md
  package.json
  public/videos/video2.mp4
  src/App.jsx
  src/components/home/Home.jsx
  src/components/home/Home.scss
  yarn.lock
Labels: Reviewed

#2 add tailwind
  package.json
  src/App.css
  src/App.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  tailwind.config.cjs
  yarn.lock
Labels: Reviewed

#6 Structure and style of cards complete + tailwind settings + images added
  package.json
  postcss.config.cjs
  public/images/jessica.jpg
  public/images/lucifer.jpeg
  public/images/narcos.jpg
  src/App.jsx
  src/components/MoviesListHome/MoviesListHome.jsx
  src/components/MoviesListHome/MoviesListHome.scss
  src/components/home/Home.jsx
  src/components/home/Home.scss
  src/main.css
  yarn.lock
Labels: Correction done, Review needed

#5 footer structure and style
  src/App.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
Labels: ready

#7 add route and pages
  .husky/pre-commit
  package.json
  src/App.jsx
  src/main.jsx
  src/pages/home/Home.jsx
  src/pages/home/Home.scss
  yarn.lock
Labels: Correction done, Conflicts resolved

#9 fixed navbar + footer design and removed unneeded code
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.scss
  src/components/navbar/Navbar.css
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.scss
  src/pages/home/Home.scss
Labels: Conflicts resolved

#8 Added all searchbar features
  src/App.jsx
  src/assets/default_img.jpg
  src/components/searchbar/Searchbar.jsx
  src/components/searchbar/Searchbar.scss
  src/pages/home/Home.jsx
  yarn.lock
Labels: Reviewed, Correction done

#11 added variables and renamed folders
  src/App.jsx
  src/App.scss
  src/components/footer/Footer.jsx
  src/components/footer/Footer.scss
  src/components/movieslisthome/MoviesListHome.jsx
  src/components/movieslisthome/MoviesListHome.scss
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.scss
  src/main.css
  src/main.jsx
  src/main.scss
  src/pages/home/Home.jsx
Labels: Correction done, Review needed

#13 S01 fix navbar
  src/components/navbar/Navbar.jsx
Labels: Reviewed

#12 S01 us10 movie detail
  package.json
  src/main.css
  src/pages/detail/Movie.jsx
  src/pages/detail/Tv.jsx
  src/pages/detail/movie.scss
  src/pages/detail/tv.scss
  yarn.lock
Labels: Correction done

#15 S01 searchbar props
  .env.sample
  package.json
  src/components/searchbar/Searchbar.jsx
  src/components/searchbar/Searchbar.scss
  src/data/genres.json
  yarn.lock
Labels: Correction done

#17 S01 us10 movie add actors
  src/pages/detail/Movie.jsx
Labels: Correction done

#20 added quiz structure and style
  package.json
  src/App.jsx
  src/assets/answer_a.svg
  src/assets/answer_b.svg
  src/assets/answer_c.svg
  src/assets/answer_d.svg
  src/components/navbar/Navbar.jsx
  src/hooks/useSize.jsx
  src/pages/quiz/Quiz.jsx
  src/pages/quiz/Quiz.scss
  yarn.lock
Labels: Correction done, Review needed

#21 add movies route
  src/App.jsx
  src/components/movieslisthome/MoviesListHome.jsx
  src/pages/detail/Movie.jsx
Labels: Correction done

#22 Category movie page
  src/App.jsx
  src/pages/typepage/CategoryPage.css
  src/pages/typepage/CategoryPage.jsx
Labels: Correction done

#24 S03 movie page improve
  src/pages/detail/Movie.jsx
Labels: Correction done

#37 S4 us10 tv show
  src/App.jsx
  src/components/movieslisthome/MoviesListHome.jsx
  src/pages/detail/Movie.jsx
  src/pages/detail/Tv.jsx
Labels: Read to Merge

#39 made movie and tv list similar
  src/components/movieslisthome/MoviesListHome.jsx
Labels: Fix

#41 added new logo
  public/images/logo.png
  src/components/navbar/Navbar.jsx
  src/components/navbar/Navbar.scss
Labels: Fix

#44 fixed placement and video speed
  src/components/searchbar/Searchbar.scss
  src/pages/home/Home.jsx
Labels: Review needed
